---
title: "Timecourse"
output: html_document
---

#read in config file
Read config.yml for the locations of sample sheet, pipeline output and sigmut loc and variants_dir
```{r, child="_settings.Rmd"}
```

# dummy data
```{r libraries}
library(plotly)

#read in sample names from sample sheet 
df <- read.table("../../tests/sample_data/test_var_timecourse.csv",sep = "\t",header = T)
df <- read.table(paste0(variant_dir,"/",test_var_timecourse.csv))
print(df)
```



```{r input and plot, echo=F}
#from rafael
#read in sample names from sample sheet 
#df <- read.table("../tests/sample_data/test_var_timecourse.csv",sep = "\t",header = T)
#print(df)
forplot<- reshape2::melt(df,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))
forplot$dates <- as.Date(forplot$dates)

locations <- unique(forplot$location_name)

plots_locations <- lapply(locations, function(location) {
  tmp <- forplot  %>% filter(location_name ==location) 
  fig <- plot_ly(x = tmp$dates,name=tmp$variable,y = tmp$value, type = 'scatter',mode = 'lines') %>%    
  layout(title = location)
  fig <- fig %>% add_markers(marker = list(line = list(color = "black", width = 1)))
})
```

# plotting the figures
```{r plot, echo=F}
plots_locations[[1]]
plots_locations[[2]]
plots_locations[[3]]
plots_locations[[4]]
plots_locations[[5]]
plots_locations[[6]]
```

# fancy plots to come: maps

# snippets
```{r,echo=F, eval=F}

for (i in unique(df$location_name)){
  name <- paste0("df_",i)
  assign(name,df[df$location_name==i,])
}


forplot<- reshape2::melt(df,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))

all_locs<-ggplot(forplot, aes(x = dates, y = 0:1, color = value)) +
ggtitle(" plot")+
geom_point(size = 0.2)+
scale_colour_gradient(low = "yellow", high = "dark blue")+
facet_wrap(~variable,ncol = 5)+
theme(strip.text = element_text(size = 8), strip.background = element_rect(size
= 0.3) )

all_locs
```




```{r,eval=F,echo=F}


forplot<- reshape2::melt(df,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long","WT","b1351","b117"))
forplot$dates <- as.Date(forplot$dates)

#subset it also to time

#var <- unique(forplot$variable)

#forplot <- forplot[forplot$variable==var[1],]

bubble<-plot_ly (
  data= forplot,
  type = 'scattergeo',
  mode='markers')

bubble <- bubble %>% add_trace(
  lon =forplot$coordinates_long ,
  lat =forplot$coordinates_lat,
  marker = list (
  color =c( 'red','red','red','red','red','red','red','red','red','red' ) ,
  size = forplot$WT*100,
  mode = 'markers' )
  )

bubble <- bubble %>% layout(
  title= "Variant x detected",
  updatemenus = list(
    list(
      type = "buttons",
      y = 1,
      buttons = list(
        
        list(method = "update",
             args = list("size","forplot$b1351*100"),
             label= "b1351"),
        
        list(method = "update",
             args = list("size","forplot$WT*100"),
             label= "WT"),
        
        list(method = "update",
             args = list("size","forplot$b117*100"),
             label= "b117")
      )
    )
  )
)

bubble
```

